### ISSUE TITLE
Make `monitor_process()` more stable

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/pybombs2#16]
In PyBOMBS1, we had code that knows which process you're running and will perform some cleanup. E.g. if you Ctrl-C during a git clone, will delete stray files afterwards. Sub-tasks:

- [x] Make sure that all child processes are killed, too
- [x] Register cleanup functions, depending on the command

**Comment by sdh11** [comment]
Should these cleanup functions also be triggered if an error occurs during the fetcher process?

**Comment by mbr0wn** [comment]
The fetcher process should be using `monitor_process()` for running git etc., so that would implicitly be covered.

**Comment by mbr0wn** [comment]
Cleanup function should be passed in as argument.

**Comment by mbr0wn** [comment]
05a6dffd720351e687ac2aa2ab28c377aad58c94
