### ISSUE TITLE
Use yaml for recipes

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/pybombs2#33]
We've had requests to use JSON, and to align the file formats for the inventory and the config. There is a precedent for using YAML with CGRAN, so how about using that everywhere? recipes, config files, and inventory files. All easily hand-editable, machine-readable, etc.

**Comment by skoslowski** [comment]
Like it. I can see YAML being used in GRC, too.

**Comment by mbr0wn** [comment]
Yeah, and the more I think about it, the more I like this too. We currently have .lwr format for recipes, ini format for config.dat and pickle format for the inventory. What the hell? Let's scrap all of this crap.

**Comment by mbr0wn** [comment]
And if we make PyYAML a dependency, that'll slash the amount of code we need to maintain, because all the parsing pain goes away.

**Comment by sdh11** [comment]
Sounds good to me.

**Comment by osh** [comment]
What would an example recipe look like?   I kind of like the current syntax but hate all the parser crap, something more standard would be nice - but wouldn't want the syntax to become more bloated or unwieldy.  Only reservations with pyyaml are introducing dependencies for pybombs is kind of a pain, kind of the goal was for it to only use python which you always have at least on almost any machine to rely on.   If we did at the dependency, we should have code to check for it and bootstrap cleanly on machines that dont have it --- presumably this could not be done from a recipe since they havent been parsed yet

**Comment by mbr0wn** [comment]
@osh that remains to be decided. The current syntax looks a lot like YAML already, so I'd guess it would look pretty similar.

Good point about the bootstrapping. plex is a dependency for PB1, and that was solved by simply copying it into the repo. Maybe that's a solution. But also, another thing I want to get rid of is having to git clone PyBOMBS. If people install it through pip, there goes that problem. If we provide a tarball, we can simply add PyYAML in there.

**Comment by osh** [comment]
https://github.com/ravenac95/simpleyaml
looks like other people have pondered this bootstrap issue -

**Comment by mbr0wn** [comment]
@osh note that simpleyaml comes from a time when PyYAML did not have a Python-only mode. Still, very interesting.

**Comment by mbr0wn** [comment]
Here's an attempt at gnuradio.lwr:
```{.yml}
depends:
    - make
    - boost
    - fftw
    - cppunit
    - swig
    - gsl
    - uhd
    - alsa
    - git
    - python
    - cheetah
    - wxpython
    - numpy
    - lxml
    - pygtk
    - pycairo
    - cmake
    - pyqt4
    - pyqwt5
    - gcc
    - apache-thrift
    - liblog4cpp
category: common
satisfy_deb: gnuradio-dev
source: git+git@github.com:gnuradio/gnuradio.git
gitbranch: master
gitargs: --recursive
vars:
	config_opt: -DENABLE_DOXYGEN=$builddocs
inherit: cmake
configure_static: cmake .. -DCMAKE_BUILD_TYPE=$cmakebuildtype -DCMAKE_INSTALL_PREFIX=$prefix -DENABLE_STATIC_LIBS=True $config_opt
install: |
    make install
    make install
```

**Comment by mbr0wn** [comment]
Updated title because except for recipes, it's all yaml now.

**Comment by mbr0wn** [comment]
625a941785fd87982c2bf1abbc8541b167642875 basically implements this. Needs more testing, though.

**Comment by mbr0wn** [comment]
Merged into master.
