### ISSUE TITLE
Prefix init command

### ISSUE THREAD

**Issue by sdh11** [gnuradio/pybombs2#4]
Command initializes an empty prefix for a new GNU Radio install. 
```
pybombs prefix init
```

**Comment by mbr0wn** [comment]
Does the following:
- [ ] Setup up required directories: `.pybombs`, `src`
- [ ] Create an environment file

**Comment by mbr0wn** [comment]
Like `git init`

**Comment by mbr0wn** [comment]
Maybe:
- Add switches to where the prefix is supposed to be created
- The alias of the prefix
- Add that location to ~/.pybombs/config.yml

**Comment by mbr0wn** [comment]
Allow a template/recipe

**Comment by mbr0wn** [comment]
init branch has something that looks like it's working

**Comment by mbr0wn** [comment]
f272a7e0c2a65a963c98bbe7c777c517c786754d
